import { BadgeCheck, BrainCircuit, Database, FlaskConical, ShieldCheck, Wrench } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import type { Memo, Story, SystemSummary } from "@/lib/data-schema";
import { formatMemoText, labelSystem, labelToken, percent } from "@/lib/utils";

type Profile = {
  profile_id: string;
  eligible_systems: string[];
  ranking: string[];
  recommendation: string;
  reason_code: string;
};

export function RecommendationSummary({
  memo,
  profiles,
  systems,
  story,
}: {
  memo: Memo;
  profiles: Profile[];
  systems: SystemSummary[];
  story: Story;
}) {
  const profile = profiles.find((item) => item.profile_id === "maximum_confirmed_capability");
  const recommendation = memo.recommendations.find((item) => item.profile_id === profile?.profile_id);
  if (!profile || !recommendation) throw new Error("maximum confirmed capability recommendation is missing");
  const selected = systems.find((system) => system.system_id === recommendation.recommended_system);
  const full = systems.find((system) => system.system_id === "target_full_retrain");
  if (!selected || !full) throw new Error("recommendation systems are missing");
  const facts = new Map(story.facts.map((fact) => [fact.fact_id, fact.display_value]));

  return (
    <Card id="executive-recommendation" className="relative overflow-hidden border-cyan-300/20 p-6 sm:p-8">
      <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-cyan-300 to-transparent" />
      <div className="flex flex-col gap-8 xl:flex-row xl:items-start xl:justify-between">
        <div className="max-w-3xl">
          <div className="flex flex-wrap items-center gap-2">
            <Badge>Executive recommendation</Badge>
            <span className="text-sm text-slate-400">{labelToken(profile.profile_id)}</span>
          </div>
          <p className="mt-6 text-sm font-semibold uppercase tracking-[0.14em] text-cyan-200">Recommendation</p>
          <h2 className="mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl">
            {labelSystem(recommendation.recommended_system)}
          </h2>
          <dl className="mt-7 grid gap-5 sm:grid-cols-2">
            <RecommendationField
              label="Applies when"
              value="Prioritize maximum confirmed capability among safety-eligible target migration methods."
            />
            <RecommendationField label="Primary reason" value={formatMemoText(recommendation.rationale)} />
            <RecommendationField
              label="Critical tradeoff"
              value={`${labelSystem(full.system_id)} performed better under adversarial pressure (${percent(full.adversarial_semantic)} versus ${percent(selected.adversarial_semantic)} semantic exactness).`}
            />
            <RecommendationField
              label="Requirements"
              value={`${selected.source_teacher_required ? "Trained source teacher; " : ""}${selected.direct_original_labels} direct original anchors; ${facts.get("hybrid-teacher-labels") ?? "—"} teacher outputs; target retraining; ${labelToken(selected.complexity)} pipeline.`}
            />
          </dl>
        </div>
        <div className="grid min-w-64 gap-3 sm:grid-cols-2 xl:grid-cols-1">
          <Status icon={<BrainCircuit className="h-4 w-4" />} label="Generated by GPT-5.6 Sol" />
          <Status icon={<Database className="h-4 w-4" />} label="Structured output" />
          <Status icon={<Wrench className="h-4 w-4" />} label="One repair" />
          <Status icon={<ShieldCheck className="h-4 w-4" />} label="Offline validation passed" />
          <Status icon={<BadgeCheck className="h-4 w-4" />} label="Claims linked to immutable evidence" />
        </div>
      </div>
      <div className="mt-7 flex items-start gap-3 rounded-xl border border-amber-300/15 bg-amber-300/5 p-4 text-sm leading-6 text-amber-100/90">
        <FlaskConical className="mt-0.5 h-4 w-4 shrink-0" />
        No method is universally best. This recommendation applies to the frozen maximum-confirmed-capability profile.
      </div>
    </Card>
  );
}

function RecommendationField({ label, value }: { label: string; value: string }) {
  return <div><dt className="text-sm font-semibold text-slate-300">{label}</dt><dd className="mt-2 text-[0.9375rem] leading-7 text-slate-400">{value}</dd></div>;
}

function Status({ icon, label }: { icon: React.ReactNode; label: string }) {
  return <div className="flex items-center gap-3 rounded-xl border border-white/8 bg-white/[0.025] px-4 py-3 text-sm font-medium text-slate-200"><span className="text-cyan-300">{icon}</span>{label}</div>;
}
